// Generated by CoffeeScript 1.6.3
$(function() {
  var aspectFit;
  aspectFit = function() {
    var bodyStyle, browserH, browserW;
    browserW = innerWidth;
    browserH = innerHeight;
    bodyStyle = $('body');
    if (browserH < browserW) {
      if (browserH * 2 < browserW) {
        return bodyStyle.css({
          width: browserH * 2,
          height: browserH
        });
      } else {
        return bodyStyle.css({
          width: browserW,
          height: browserW / 2
        });
      }
    } else {
      if (browserW * 2 < browserH) {
        return bodyStyle.css({
          width: browserW,
          height: browserW * 2
        });
      } else {
        return bodyStyle.css({
          width: browserH / 2,
          height: browserH
        });
      }
    }
  };
  aspectFit();
  return $(window).on('resize', function() {
    return aspectFit();
  });
});
