// Generated by CoffeeScript 1.6.3
$(function() {
  return $('#checkButton').on('click', function() {
    var ItemNum, chkItem, i, msgTxt, _i, _len;
    chkItem = $('.checkList:checked');
    ItemNum = chkItem.length;
    msgTxt = [];
    msgTxt.push('チェック：', ItemNum, '<br>');
    for (_i = 0, _len = chkItem.length; _i < _len; _i++) {
      i = chkItem[_i];
      msgTxt.push(i.value);
    }
    if (ItemNum === 12) {
      msgTxt.push('猫');
    }
    return $('#message').html(msgTxt.join(''));
  });
});
